let arraySanPham = [
    {
        "id" : 0,
        "ten" : "STOP THINK BOXY TEE",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Badhabits",
        "dongia" : 420000,
        "tonkho" : 38,
        "mota" : "FORM BOXY\nFeatures:\n• Chất liệu: Cotton\n• Size: S, M, L, XL\n• Kỹ thuật: Nhãn ép",
        "hinh_truoc" : "../imgs/products/0_truoc.webp",
        "hinh_sau" : "../imgs/products/0_sau.webp"
    },
    {
        "id" : 1,
        "ten" : "BAD CYBORG IS SLEEPIN'",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Badhabits",
        "dongia" : 400000,
        "tonkho" : 42,
        "mota" : "FORM OVERSIZE\nFeatures:\n• Chất liệu: Cotton\n• Size: S, M, L, XL\n• Kỹ thuật: In",
        "hinh_truoc" : "../imgs/products/1_truoc.webp",
        "hinh_sau" : "../imgs/products/1_sau.webp"
    },
    {
        "id" : 2,
        "ten" : "DEJAVU BOXY TEE - GREY",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Badhabits",
        "dongia" : 400000,
        "tonkho" : 92,
        "mota" : "FORM BOXY\nFeatures:\n• Chất liệu: Cotton\n• Size: S, M, L, XL\n• Kỹ thuật: In",
        "hinh_truoc" : "../imgs/products/2_truoc.webp",
        "hinh_sau" : "../imgs/products/2_sau.webp"
    },
    {
        "id" : 3,
        "ten" : "Polo Outerity Collection TÉ",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Outerity",
        "dongia" : 165000,
        "tonkho" : 32,
        "mota" : "TUYỆT ĐỐI KHÔNG đổ nước giặt, bột giặt trực tiếp vào sản phẩm. Như vậy sẽ ảnh hưởng đến màu sắc của sản phẩm và làm cho áo có tình trạng loang màu. Outerity xin cảm ơn ạ",
        "hinh_truoc" : "../imgs/products/3_truoc.webp",
        "hinh_sau" : "../imgs/products/3_sau.webp"
    },
    {
        "id" : 4,
        "ten" : "DOUBLE DESTROYED BAGGY SHORT",
        "danhmuc" : "Quần",
        "loaihang" : "quan-ngan",
        "nhasanxuat" : "Badhabits",
        "dongia" : 750000,
        "tonkho" : 72,
        "mota" : "FORM Baggy\nFeatures:\n• Chất liệu: Cotton\n• Size: S, M, L, XL\n• Kỹ thuật: Wash, Knee, Đánh tưa",
        "hinh_truoc" : "../imgs/products/4_truoc.webp",
        "hinh_sau" : "../imgs/products/4_sau.webp"
    },
    {
        "id" : 5,
        "ten" : "\"I'M A BADSTAR\" BAGGY SHORT",
        "danhmuc" : "Quần",
        "loaihang" : "quan-ngan",
        "nhasanxuat" : "Badhabits",
        "dongia" : 750000,
        "tonkho" : 43,
        "mota" : "FORM Baggy\nFeatures:\n• Chất liệu: Cotton\n• Size: S, M, L, XL\n• Kỹ thuật: Wash, Knee, Đánh tưa",
        "hinh_truoc" : "../imgs/products/5_truoc.webp",
        "hinh_sau" : "../imgs/products/5_sau.webp"
    },
    {
        "id" : 6,
        "ten" : "METAL LABEL BAGGY SHORT",
        "danhmuc" : "Quần",
        "loaihang" : "quan-ngan",
        "nhasanxuat" : "Badhabits",
        "dongia" : 750000,
        "tonkho" : 28,
        "mota" : "Features:\n\n• Chất liệu: Jeans\n•Size: S M L XL\n• Kỹ thuật: Wash",
        "hinh_truoc" : "../imgs/products/6_truoc.webp",
        "hinh_sau" : "../imgs/products/6_sau.webp"
    },
    {
        "id" : 7,
        "ten" : "DISSTRESS BAD DENIM LABEL",
        "danhmuc" : "Quần",
        "loaihang" : "quan-dai",
        "nhasanxuat" : "Badhabits",
        "dongia" : 750000,
        "tonkho" : 15,
        "mota" : "Features:\n\n• Chất liệu: Jeans\n•Size: S M L XL\n• Kỹ thuật: Wash và Bắn Laser",
        "hinh_truoc" : "../imgs/products/7_truoc.webp",
        "hinh_sau" : "../imgs/products/7_sau.webp"
    },
    {
        "id" : 8,
        "ten" : "TRIPLET RABBIT BACKPACK",
        "danhmuc" : "Ba lô",
        "loaihang" : "phukien-balo",
        "nhasanxuat" : "Badhabits",
        "dongia" : 750000,
        "tonkho" : 2,
        "mota" : "Features:\n\n• Chất liệu: Poly\n• Kỹ thuật: Chằn phao, có Thỏ nhỏ đính kèm\n• One size fit all, Form Backpack phù hợp khi mang đi học, đi du lịch hay các hoạt động dã ngoại ngoài trời...",
        "hinh_truoc" : "../imgs/products/8_truoc.webp",
        "hinh_sau" : "../imgs/products/8_sau.webp"
    },
    {
        "id" : 9,
        "ten" : "EXTROVERT RB CROSS BAG",
        "danhmuc" : "Túi",
        "loaihang" : "phukien-tui",
        "nhasanxuat" : "Badhabits",
        "dongia" : 500000,
        "tonkho" : 3,
        "mota" : "Features:\n\n• Chất liệu: Polyeste\n• Kỹ thuật: Gắn mạc cao su, chằn gòn, thêu họa tiết Thỏ",
        "hinh_truoc" : "../imgs/products/9_truoc.webp",
        "hinh_sau" : "../imgs/products/9_sau.webp"
    },
    {
        "id" : 10,
        "ten" : "RABBIT CARTOON BACKPACK",
        "danhmuc" : "Ba lô",
        "loaihang" : "phukien-balo",
        "nhasanxuat" : "Badhabits",
        "dongia" : 700000,
        "tonkho" : 3,
        "mota" : "Features:\n\n•Chất liệu: Dù - Chống thấm nước cực tốt Tag mặt trước và logo thêu trực tiếp lên bề mặt backpack\n•Thiết kế Rolltop: để dễ dàng thay đổi diện tích chứa đồ khi cần cho các chuyến đi du lịch gần, xa Túi nhỏ ở 2 bên để có thể đựng các vật dụng nhỏ cần thiết",
        "hinh_truoc" : "../imgs/products/10_truoc.webp",
        "hinh_sau" : "../imgs/products/10_sau.webp"
    },
    {
        "id" : 11,
        "ten" : "VERPRINT BACKPACK",
        "danhmuc" : "Ba lô",
        "loaihang" : "phukien-balo",
        "nhasanxuat" : "Badhabits",
        "dongia" : 720000,
        "tonkho" : 5,
        "mota" : "Features:\n\n•Chất liệu: Dù - Chống thấm nước cực tốt Tag mặt trước và logo thêu trực tiếp lên bề mặt backpack\n•Kỹ thuật: Tên thương hiệu được thêu xù mặt trước và in trên toàn sản phẩm",
        "hinh_truoc" : "../imgs/products/11_truoc.webp",
        "hinh_sau" : "../imgs/products/11_sau.webp"
    },
    {
        "id" : 12,
        "ten" : "Outerity Winter Night Double Zip Jacket",
        "danhmuc" : "Áo",
        "loaihang" : "ao-khoac",
        "nhasanxuat" : "Outerity",
        "dongia" : 285000,
        "tonkho" : 12,
        "mota" : "!!LƯU Ý •Khi giặt sản phẩm bằng tay: Vui lòng hoà tan kĩ nước giặt, bột giặt với nước sau đó mới cho sản phẩm vào. ▪️Khi giặt sản phẩm bằng máy giặt: Vui lòng đổ nước giặt, bột giặt vào khay của máy.",
        "hinh_truoc" : "../imgs/products/12_truoc.webp",
        "hinh_sau" : "../imgs/products/12_sau.webp"
    },
    {
        "id" : 13,
        "ten" : "BADHABITS PARACHUTE",
        "danhmuc" : "Quần",
        "loaihang" : "quan-dai",
        "nhasanxuat" : "Badhabits",
        "dongia" : 690000,
        "tonkho" : 12,
        "mota" : "Features:\n\n• Chất liệu: Jeans\n•Size: S M L XL\n• Kỹ thuật: Wash và Thuê",
        "hinh_truoc" : "../imgs/products/13_truoc.webp",
        "hinh_sau" : "../imgs/products/13_sau.webp"
    },
    {
        "id" : 14,
        "ten" : "GREY 3L TRACK PANTS",
        "danhmuc" : "Quần",
        "loaihang" : "quan-dai",
        "nhasanxuat" : "Badhabits",
        "dongia" : 600000,
        "tonkho" : 19,
        "mota" : "Features:\n\n• Chất liệu: Cotton\n•Size: S M L XL\n• 3 Line độc lạ",
        "hinh_truoc" : "../imgs/products/14_truoc.webp",
        "hinh_sau" : "../imgs/products/14_sau.webp"
    },
    {
        "id" : 15,
        "ten" : "Logo Football Jersey",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "DirtyCoins",
        "dongia" : 450000,
        "tonkho" : 12,
        "mota" : "Chi tiết sản phẩm:\n• Kích thước: M - L - XL\n• Chất liệu: Polyester.\n• Relaxed Fit.\n• Hình in mặt trước và mặt sau áo áp dụng kĩ thuật in kéo lụa.\n• Nhãn Jersey trang trí được may ở góc dưới thân trước.",
        "hinh_truoc" : "../imgs/products/15_truoc.webp",
        "hinh_sau" : "../imgs/products/15_sau.webp"
    },
    {
        "id" : 16,
        "ten" : "Outerity Line Dino Tee",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Outerity",
        "dongia" : 179000,
        "tonkho" : 82,
        "mota" : "!!LƯU Ý •Khi giặt sản phẩm bằng tay: Vui lòng hoà tan kĩ nước giặt, bột giặt với nước sau đó mới cho sản phẩm vào. ▪️Khi giặt sản phẩm bằng máy giặt: Vui lòng đổ nước giặt, bột giặt vào khay của máy.",
        "hinh_truoc" : "../imgs/products/16_truoc.webp",
        "hinh_sau" : "../imgs/products/16_sau.webp" 
    },
    {
        "id" : 17,
        "ten" : "YOUR SHADOW TEE",
        "danhmuc" : "Áo",
        "loaihang" : "ao-thun",
        "nhasanxuat" : "Badhabits",
        "dongia" : 400000,
        "tonkho" : 19,
        "mota" : "Features:\n\n• Chất liệu: Cotton\n•Size: S M L XL\n• Kỹ thuật: In tràn thân trước",
        "hinh_truoc" : "../imgs/products/17_truoc.webp",
        "hinh_sau" : "../imgs/products/17_sau.webp"
    },
    {
        "id" : 18,
        "ten" : "TOO LAZY TO WEAR JACKET JEANS",
        "danhmuc" : "Áo",
        "loaihang" : "ao-khoac",
        "nhasanxuat" : "Badhabits",
        "dongia" : 900000,
        "tonkho" : 10,
        "mota" : "Features:\n\n• Chất liệu: Jeans\n•Size: S M L XL\n• Kỹ thuật: Wash và Bắn Laser",
        "hinh_truoc" : "../imgs/products/18_truoc.webp",
        "hinh_sau" : "../imgs/products/18_sau.webp"
    }
]